"""create suroviny table

Revision ID: d4fa85981759
Revises: 
Create Date: 2026-07-23 12:14:28.255373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4fa85981759'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suroviny',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazev', sa.String(), nullable=False),
    sa.Column('velikost_baleni', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('minimalni_mnozstvi', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suroviny_id'), 'suroviny', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suroviny_id'), table_name='suroviny')
    op.drop_table('suroviny')
    # ### end Alembic commands ###
